language: python2

sudo: required

services:
    - docker

before_install:
    - docker build -t qe:latest-atlas-mpich .

script:
    - docker run -it --entrypoint "/home/qe/simple-test.sh" qe:latest-atlas-mpich

